export const MONTH_NAMES = [{
  'name': 'January',
  'abbr': 'Jan'
}, {
  'name': 'February',
  'abbr': 'Feb'
}, {
  'name': 'March',
  'abbr': 'Mar'
}, {
  'name': 'April',
  'abbr': 'Apr'
}, {
  'name': 'May',
  'abbr': 'May'
}, {
  'name': 'June',
  'abbr': 'Jun'
}, {
  'name': 'July',
  'abbr': 'Jul'
}, {
  'name': 'August',
  'abbr': 'Aug'
}, {
  'name': 'September',
  'abbr': 'Sep'
}, {
  'name': 'October',
  'abbr': 'Oct'
}, {
  'name': 'November',
  'abbr': 'Nov'
}, {
  'name': 'December',
  'abbr': 'Dec'
}];

export const WEEK_DAY_NAMES = [{
  'name': 'Sunday',
  'abbr': 'Sun'
}, {
  'name': 'Monday',
  'abbr': 'Mon'
}, {
  'name': 'Tuesday',
  'abbr': 'Tue'
}, {
  'name': 'Wednesday',
  'abbr': 'Wed'
}, {
  'name': 'Thursday',
  'abbr': 'Thu'
}, {
  'name': 'Friday',
  'abbr': 'Fri'
}, {
  'name': 'Saturday',
  'abbr': 'Sat'
}, ];